# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Auto format

on:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1.3.1
        with:
          github_token: ${{ github.token }}

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto format (buf)
        run: |
          buf format -w
      - name: Commit changes (buf)
        run: |
          git add -u
          git commit -m 'style: `buf format -w`' || true

      - name: Auto format (java)
        run: |
          cd java/
          ./mvnw -s settings.xml -Pformat
      - name: Commit changes (java)
        run: |
          git add -u
          git commit -m 'style: `./mvnw -settings.xml -Pformat`' || true

      - name: Auto format (prettier)
        run: |
          git ls-files '*.js' '*.yml' '*.yaml' '*.json' '*.md' -z | xargs -0 pnpm exec prettier --write
      # Cannot modify .github/workflows (refusing to allow a GitHub App to create or update workflow)
      - name: Ignore github workflows
        run: |
          git checkout .github/workflows
      - name: Commit changes (prettier)
        run: |
          git add -u
          git commit -m 'style: `prettier --write`' || true

      - name: Push changes
        run: |
          git push
